#!/bin/bash

# [Projeto]
# Sticker de Inicialização do TigerOS

# [Autores]
# Equipe TigerOS
# 

#. /usr/lib/tiger-os/tiger-osd.sh

HERE="$(dirname "$(readlink -f "${0}")")"

[ "${XDG_CONFIG_HOME}" = "" ] && {
  export XDG_CONFIG_HOME="${HOME}/.config"
}

[ -f "${XDG_CONFIG_HOME}/alerta_de_videos" ] && {
  exit 
}

export GTK_THEME=Adwaita:dark

nao_mostrar_novamente=$(yad \
    --center \
    --borders=32 \
    --image="${HERE}/logoNew.png" \
    --sticky --undecorated --skip-taskbar --no-focus --fixed \
    --text='<span size="large"><b>Quer aprender sobre como usar o TigerOS?</b>\nTemos várias aulas!\n<b>Vamos assistir agora?</b></span>' \
    --text-align="left" \
    --form --field="Não mostrar mais":CHK \n \
    --button=gtk-open:42 \
    --button=gtk-close)
    
[ "${nao_mostrar_novamente}" = "TRUE|" ] && {
  touch "${XDG_CONFIG_HOME}/alerta_de_videos"
}

[ "${?}" = "42" ] && /var/lib/curso-linux/curso-linux
